routes/web.php
<?php

use App\Http\Controllers\OrderEntriesController;
use App\Http\Controllers\OrderGroupsController;
use App\Http\Controllers\PartyInfosController;
use App\Http\Controllers\SlipsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::delete('partyInfos/trash/{partyInfo}', [PartyInfosController::class, 'trash'])->name('partyInfos.trash')->middleware(['auth']);
Route::get('partyInfos/trashed', [PartyInfosController::class, 'trashed'])->name('partyInfos.trashed')->middleware(['auth']);
Route::put('partyInfos/restore/{partyInfo}', [PartyInfosController::class, 'restore'])->name('partyInfos.restore')->middleware(['auth']);
Route::resource('partyInfos', PartyInfosController::class)->middleware(['auth']);
Route::resource('slips', SlipsController::class)->middleware(['auth']);
Route::resource('slips.orderGroups', OrderGroupsController::class)->except(['index', 'show'])->middleware(['auth']);
Route::resource('orderGroups.orderEntries', OrderEntriesController::class)->except(['index', 'show'])->middleware(['auth']);


require __DIR__ . '/auth.php';

app/Models/PartyInfo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PartyInfo extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = ['id'];

    public function partySlips()
    {
        return $this->hasMany(Slip::class)->orderBy('bill_date');
    }

    public function getSlipCountAttribute()
    {
        return $this->partySlips()->count() ? 'btn-success' : 'btn-danger';
    }
}

resources/views/partyAddress/create.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card mb-2">
    <div class="card-header"><h2>Add New Party</h2></div>
        <div class="card-body">
            <form action="{{  route('partyInfos.store')  }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="company_name">Party Name</label>
                    <input type="text"
                            class="form-control @error('company_name') is-invalid @enderror"
                            name="company_name"
                            value="{{ old('company_name') }}"
                            placeholder="Enter Party Name"
                            id="company_name">
                    @error('company_name')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="contact_no">Contact No</label>
                    <input type="number"
                            class="form-control @error('contact_no') is-invalid @enderror"
                            name="contact_no"
                            value="{{ old('contact_no') }}"
                            placeholder="Enter Contact Number"
                            id="contact_no">
                    @error('contact_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email"
                            class="form-control @error('email') is-invalid @enderror"
                            name="email"
                            value="{{ old('email') }}"
                            placeholder="Enter Email Address"
                            id="email">
                    @error('email')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="GST_no">GST No</label>
                    <input type="text"
                            class="form-control @error('GST_no') is-invalid @enderror"
                            name="GST_no"
                            value="{{ old('GST_no') }}"
                            placeholder="Enter GST Number"
                            id="GST_no">
                    @error('GST_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="state">State</label>
                    <input type="text"
                            class="form-control @error('state') is-invalid @enderror"
                            name="state"
                            value="{{ old('state') }}"
                            placeholder="Enter Your State"
                            id="state">
                    @error('state')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="company_address">Address</label>
                    <textarea name="company_address"
                                id="company_address"
                                cols="30"
                                rows="5"
                                class="form-control @error('company_address') is-invalid @enderror"
                                placeholder="Enter Party Address"></textarea>
                    @error('company_address')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/partyAddress/edit.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card mb-2">
    <div class="card-header"><h2>Add New Party</h2></div>
        <div class="card-body">
            <form action="{{  route('partyInfos.update', $partyInfo->id)  }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="company_name">Party Name</label>
                    <input type="text"
                            class="form-control @error('company_name') is-invalid @enderror"
                            name="company_name"
                            value="{{ old('company_name', $partyInfo->company_name) }}"
                            placeholder="Enter Party Name"
                            id="company_name">
                    @error('company_name')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="contact_no">Contact No</label>
                    <input type="number"
                            class="form-control @error('contact_no') is-invalid @enderror"
                            name="contact_no"
                            value="{{ old('contact_no', $partyInfo->contact_no) }}"
                            placeholder="Enter Contact Number"
                            id="contact_no">
                    @error('contact_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email"
                            class="form-control @error('email') is-invalid @enderror"
                            name="email"
                            value="{{ old('email', $partyInfo->email) }}"
                            placeholder="Enter Email Address"
                            id="email">
                    @error('email')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="GST_no">GST No</label>
                    <input type="text"
                            class="form-control @error('GST_no') is-invalid @enderror"
                            name="GST_no"
                            value="{{ old('GST_no', $partyInfo->GST_no) }}"
                            placeholder="Enter GST Number"
                            id="GST_no">
                    @error('GST_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="state">State</label>
                    <input type="text"
                            class="form-control @error('state') is-invalid @enderror"
                            name="state"
                            value="{{ old('state', $partyInfo->state) }}"
                            placeholder="Enter Your State"
                            id="state">
                    @error('state')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="company_address">Address</label>
                    <textarea name="company_address"
                                id="company_address"
                                cols="30"
                                rows="5"
                                class="form-control @error('company_address') is-invalid @enderror"
                                placeholder="Enter Party Address">{{ old('company_address', $partyInfo->company_address) }}</textarea>
                    @error('company_address')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/partyAddress/index.blade.php
@extends('layouts.billGeneration.app')

@section('content')
    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('partyInfos.create') }}" class="btn btn-outline-primary">Add a Party</a>
    </div>
    <div class="card ">
        <div class="card-header"><h4>All Parties</h4></div>
            <div class="card-body">
                <div class="media">
                    <div class="mr-4 statistics">
                        <div class="votes text-center mb-4">
                            {{-- <strong class="d-block">{{ $question->votes_count }}</strong> Slips --}}
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Contact</th>
                                    <th>Email</th>
                                    <th>GST</th>
                                    <th>State</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($parties as $party)
                                    <tr>
                                        <td><a href="{{ route('partyInfos.show', $party->id) }}">{{$party->company_name}}</a></td>
                                        <td>{{$party->contact_no}}</td>
                                        <td>{{$party->email}}</td>
                                        <td>{{$party->GST_no}}</td>
                                        <td>{{$party->state}}</td>
                                        <td>
                                            <a href="{{ route('partyInfos.edit', $party->id) }}" class="btn btn-sm btn-primary mb-1">
                                                Edit
                                            </a>
                                            <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $party->id }})" data-toggle="modal" data-target="#deleteModal">
                                                Trash
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
<!-- Delete Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel">Trash Party</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <form action="" method="POST" id="trashPartyForm">
                                        @csrf
                                        @method('DELETE')
                                        <div class="modal-body">
                                            Are you sure, you want to Trash this Party?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-outline-danger">Trash Party</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mt-5 ml-3">
                    {{ $parties->links('vendor.pagination.bootstrap-4') }}
                </div>
            </div>
        </div>
    </div>
@endsection



{{--
<div class="card">
    <div class="card-header"><h2>Posts</h2></div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                @if(auth()->user()->isAdmin())
                    <th>User</th>
                @endif
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    @if(!(auth()->user()->isAdmin()))
                    <th>Status</th>
                    @endif
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                    <tr>
                    @if(auth()->user()->isAdmin())
                        <td>{{ $post->author->name }}</td>
                    @endif
                        <td><img src="{{ asset($post->image_path) }}" width="120"></td>
                        <td>{{$post->title}}</td>
                        <td>{{$post->excerpt}}</td>
                        <td>{{$post->category->name}}</td>
                        @if(!(auth()->user()->isAdmin()))
                        <td>
                            <span class="btn btn-sm {{$post->approved ? 'btn-outline-success' : 'btn-outline-danger'}}">
                                {{$post->approved ? 'Approved' : 'Disapproved'}}
                            </span>
                        </td>
                        @endif
                        <td>
                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">
                                Edit
                            </a>
                            <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $post->id }})" data-toggle="modal" data-target="#deleteModal">
                                Trash
                            </button>
                            @if(auth()->user()->isAdmin())
                            <div class="mt-2">
                                <form action="{{route('posts.status', $post->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')

                                    <button type="submit" class="btn btn-sm {{$post->approved ? 'btn-outline-danger' : 'btn-outline-success'}}">
                                    @if (! $post->approved)
                                        Approve <i class="fa fa-check"></i>
                                    @else
                                        Disapprove <i class="fa fa-times"></i>
                                    @endif
                                    </button>

                                </form>
                            </div>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Trash post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="trashPostForm">
            @csrf
            @method('DELETE')
        <div class="modal-body">
          Are you sure, you want to Trash this Post?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-outline-danger">Trash Post</button>
        </div>
        </form>
      </div>
    </div>
  </div>

<div class="mt-5">
    {{ $posts->links('vendor.pagination.bootstrap-4') }}
</div>

@endsection --}}

@section('page-level-scripts')
<script>
    function displayModal(partyId) {
        var url = "/partyInfos/trash/" + partyId;
        $("#trashPartyForm").attr('action', url);
    }
</script>
@endsection

resources/views/partyAddress/show.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card col-md-10 p-3">
    <div class="card-header">
        <h4>
            {{$partyInfo->company_name}}
            <span class="ml-4 btn {{$partyInfo->slip_count}}">
                {{$partyInfo->partySlips()->count()}} Slips
            </span>
        </h4>

        <table class="table">
                <tr>
                    <th>Contact</th>
                    <td>{{$partyInfo->contact_no}}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{$partyInfo->email}}</td>
                </tr>
                <tr>
                    <th>GST</th>
                    <td>{{$partyInfo->GST_no}}</td>
                </tr>
                <tr>
                    <th>Adress</th>
                    <td>{{$partyInfo->company_address}}</td>
                </tr>
                <tr>
                    <th>State</th>
                    <td>{{$partyInfo->state}}</td>
                </tr>
        </table>
    </div>
</div>
@if($partyInfo->partySlips()->count())
<div class="card p-3 mt-2 mb-2">
    <div class="card-body">
        @foreach ($partyInfo->partySlips as $partySlip)
        <a href="#" class="btn btn-warning mb-2 mr-2">
            <div class="d-inline">
                <table class="table d-inline">
                    <tr>
                        <th>Serial No</th>
                        <th>Slip Date</th>
                        <th>Meter</th>
                        <th>Taga</th>
                    </tr>
                    <tr>
                        <td>{{$partySlip->serial_no}}</td>
                        <td>{{explode(" ",$partySlip->bill_date)[0]}}</td>
                        <td>{{$partySlip->total_meter}} </td>
                        <td>{{ $partySlip->total_piece}}</td>
                    </tr>
                </table>
            </div>
        </a>
        @endforeach
    </div>
</div>
@endif
@endsection

resources/views/partyAddress/trashed.blade.php
@extends('layouts.billGeneration.app')

@section('content')
    <div class="card ">
        <div class="card-header"><h4>Trashed Parties</h4></div>
            <div class="card-body">
                <div class="media">
                    <div class="mr-4 statistics">
                        <div class="votes text-center mb-4">
                            {{-- <strong class="d-block">{{ $question->votes_count }}</strong> Slips --}}
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Contact</th>
                                    <th>Email</th>
                                    <th>GST</th>
                                    <th>State</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($parties as $party)
                                    <tr>
                                        <td><a href="{{ route('partyInfos.show', $party->id) }}">{{$party->company_name}}</a></td>
                                        <td>{{$party->contact_no}}</td>
                                        <td>{{$party->email}}</td>
                                        <td>{{$party->GST_no}}</td>
                                        <td>{{$party->state}}</td>
                                        <td>
                                            <form action="{{route('partyInfos.restore', $party->id)}}" method="POST">
                                                @csrf
                                                @method('PUT')
                                            <button type="submit" class="btn btn-sm btn-primary mb-1">Restore</button>
                                            </form>
                                            <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $party->id }})" data-toggle="modal" data-target="#deleteModal">
                                                Delete
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
<!-- Delete Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel">Trash Party</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <form action="" method="POST" id="deletePartyForm">
                                        @csrf
                                        @method('DELETE')
                                        <div class="modal-body">
                                            Are you sure, you want to Delete this Party?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-outline-danger">Delete Party</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mt-5 ml-3">
                    {{ $parties->links('vendor.pagination.bootstrap-4') }}
                </div>
            </div>
        </div>
    </div>
@endsection



{{--
<div class="card">
    <div class="card-header"><h2>Posts</h2></div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                @if(auth()->user()->isAdmin())
                    <th>User</th>
                @endif
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    @if(!(auth()->user()->isAdmin()))
                    <th>Status</th>
                    @endif
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                    <tr>
                    @if(auth()->user()->isAdmin())
                        <td>{{ $post->author->name }}</td>
                    @endif
                        <td><img src="{{ asset($post->image_path) }}" width="120"></td>
                        <td>{{$post->title}}</td>
                        <td>{{$post->excerpt}}</td>
                        <td>{{$post->category->name}}</td>
                        @if(!(auth()->user()->isAdmin()))
                        <td>
                            <span class="btn btn-sm {{$post->approved ? 'btn-outline-success' : 'btn-outline-danger'}}">
                                {{$post->approved ? 'Approved' : 'Disapproved'}}
                            </span>
                        </td>
                        @endif
                        <td>
                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">
                                Edit
                            </a>
                            <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $post->id }})" data-toggle="modal" data-target="#deleteModal">
                                Trash
                            </button>
                            @if(auth()->user()->isAdmin())
                            <div class="mt-2">
                                <form action="{{route('posts.status', $post->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')

                                    <button type="submit" class="btn btn-sm {{$post->approved ? 'btn-outline-danger' : 'btn-outline-success'}}">
                                    @if (! $post->approved)
                                        Approve <i class="fa fa-check"></i>
                                    @else
                                        Disapprove <i class="fa fa-times"></i>
                                    @endif
                                    </button>

                                </form>
                            </div>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Trash post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="trashPostForm">
            @csrf
            @method('DELETE')
        <div class="modal-body">
          Are you sure, you want to Trash this Post?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-outline-danger">Trash Post</button>
        </div>
        </form>
      </div>
    </div>
  </div>

<div class="mt-5">
    {{ $posts->links('vendor.pagination.bootstrap-4') }}
</div>

@endsection --}}

@section('page-level-scripts')
<script>
    function displayModal(partyId) {
        var url = "/partyInfos/" + partyId;
        $("#deletePartyForm").attr('action', url);
    }
</script>
@endsection