routes/web.php
<?php

use App\Http\Controllers\OrderEntriesController;
use App\Http\Controllers\OrderGroupsController;
use App\Http\Controllers\PartyInfosController;
use App\Http\Controllers\SlipsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::delete('partyInfos/trash/{partyInfo}', [PartyInfosController::class, 'trash'])->name('partyInfos.trash')->middleware(['auth']);
Route::get('partyInfos/trashed', [PartyInfosController::class, 'trashed'])->name('partyInfos.trashed')->middleware(['auth']);
Route::put('partyInfos/restore/{partyInfo}', [PartyInfosController::class, 'restore'])->name('partyInfos.restore')->middleware(['auth']);
Route::resource('partyInfos', PartyInfosController::class)->middleware(['auth']);
Route::resource('slips', SlipsController::class)->middleware(['auth']);
Route::resource('slips.orderGroups', OrderGroupsController::class)->except(['index', 'show'])->middleware(['auth']);
Route::resource('orderGroups.orderEntries', OrderEntriesController::class)->except(['index', 'show'])->middleware(['auth']);


require __DIR__ . '/auth.php';

app/Models/OrderEntry.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderEntry extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public static function boot()
    {
        parent::boot();
        static::created(function (OrderEntry $orderEntry) {
            $orderEntry->baleGroup->slip->total_meter = $orderEntry->baleGroup->slip->total_meter + $orderEntry->meter;
            $orderEntry->baleGroup->group_total_meter = $orderEntry->baleGroup->group_total_meter + $orderEntry->meter;
            $orderEntry->baleGroup->slip->increment('total_piece');
            $orderEntry->save();
            $orderEntry->baleGroup->save();
            $orderEntry->baleGroup->slip->save();
        });
        static::deleted(function (OrderEntry $orderEntry) {
            $meter = $orderEntry->meter;
            $orderEntry->baleGroup->slip->update([
                'total_meter' => $orderEntry->baleGroup->slip->total_meter - $meter,
                'total_piece' => $orderEntry->baleGroup->slip->total_piece - 1,
            ]);
            $orderEntry->baleGroup->update([
                'group_total_meter' => $orderEntry->baleGroup->group_total_meter - $meter
            ]);
        });
    }
    public function baleGroup()
    {
        return $this->belongsTo(OrderGroup::class, 'order_group_id');
    }

    public function scopeUpdateSum()
    {
        $this->baleGroup->slip->total_meter = $this->baleGroup->slip->total_meter - $this->meter;
        $this->baleGroup->slip->save();
        $this->baleGroup->group_total_meter = $this->baleGroup->group_total_meter - $this->meter;
        $this->baleGroup->save();
    }
}

app/Http/Controllers/OrderEntriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderEntry\CreateOrderEntryRequest;
use App\Http\Requests\OrderEntry\UpdateOrderEntryRequest;
use App\Models\OrderEntry;
use App\Models\OrderGroup;
use Illuminate\Http\Request;


class OrderEntriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(OrderGroup $orderGroup)
    {
        return view('orderEntry.create', compact(['orderGroup']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateOrderEntryRequest $request, OrderGroup $orderGroup)
    {
        $orderGroup->baleEntries()->create([
            'loom_no' => (int)$request->loom_no,
            'piece_no' => $request->piece_no,
            'meter' => (float)$request->meter,
        ]);
        session()->flash('success', 'Entry has been made successfully!');
        return redirect(route('orderGroups.orderEntries.create', $orderGroup->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\OrderEntry  $orderEntry
     * @return \Illuminate\Http\Response
     */
    public function show(OrderEntry $orderEntry)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\OrderEntry  $orderEntry
     * @return \Illuminate\Http\Response
     */
    public function edit(OrderGroup $orderGroup, OrderEntry $orderEntry)
    {
        return view('orderEntry.edit', compact(['orderGroup', 'orderEntry']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\OrderEntry  $orderEntry
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateOrderEntryRequest $request, OrderGroup $orderGroup, OrderEntry $orderEntry)
    {
        $difference = $request->meter - $orderEntry->meter;
        $orderEntry->update([
            'loom_no' => (int)$request->loom_no,
            'piece_no' => $request->piece_no,
            'meter' => (float)$request->meter,
        ]);
        if ($difference != 0) {
            $orderGroup->update([
                'group_total_meter' => $orderGroup->group_total_meter + $difference,
            ]);
            $orderGroup->slip->update([
                'total_meter' => $orderGroup->slip->total_meter + $difference
            ]);
        }
        session()->flash('success', 'Entry has been Updated successfully!');
        return redirect(route('orderGroups.orderEntries.create', $orderGroup->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\OrderEntry  $orderEntry
     * @return \Illuminate\Http\Response
     */
    public function destroy(OrderGroup $orderGroup, OrderEntry $orderEntry)
    {
        $orderEntry->delete();
        session()->flash('success', 'Entry has been Deleted successfully!');
        return redirect(route('orderGroups.orderEntries.create', $orderGroup->id));
    }
}

resources/views/orderEntry/create.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card mb-2 col-md-5">
    <div class="card-header"><h2>Create New Entry</h2></div>
        <div class="card-body">
            <form action="{{route('orderGroups.orderEntries.store', $orderGroup->id)}}" method="POST">
                @csrf

                <div class="form-group">
                    <label for="bale_no">Loom No</label>
                    <input type="number"
                            class="form-control @error('loom_no') is-invalid @enderror"
                            name="loom_no"
                            value="{{ old('loom_no') }}"
                            placeholder="Enter Loom Number"
                            id="loom_no">
                    @error('loom_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="piece_no">Piece No</label>
                    <input type="text"
                            class="form-control @error('piece_no') is-invalid @enderror"
                            name="piece_no"
                            value="{{ old('piece_no') }}"
                            placeholder="Enter Piece Number"
                            id="piece_no">
                    @error('piece_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="meter">Meter</label>
                    <input type="number"
                            step="0.01"
                            class="form-control @error('meter') is-invalid @enderror"
                            name="meter"
                            value="{{ old('meter') }}"
                            placeholder="Enter Meter"
                            id="meter">
                    @error('meter')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
@if($orderGroup->baleEntries->count())
<div class="card mx-auto mb-2 col-md-12">
    <a href="{{route('slips.orderGroups.create', $orderGroup->slip->id)}}" class="btn btn-success mt-2">Complete This Bale</a>
    <div class="card-header"><h2>Existing Entries</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Loom No</th>
                        <th>Piece No</th>
                        <th>Meter</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($orderGroup->baleEntries as $orderEntry)
                        <tr>
                            <td>{{$orderEntry->loom_no}}</td>
                            <td>{{$orderEntry->piece_no}}</td>
                            <td>{{$orderEntry->meter}}</td>
                            <td>
                                <a href="{{route('orderGroups.orderEntries.edit', [$orderGroup->id, $orderEntry->id])}}" class="btn btn-sm btn-primary mb-1">
                                    Edit
                                </a>
                                <form action="{{route('orderGroups.orderEntries.destroy', [$orderGroup->id, $orderEntry->id])}}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm btn-danger">Trash</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/orderEntry/edit.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card mb-2 col-md-5">
    <div class="card-header"><h2>Edit Entry</h2></div>
        <div class="card-body">
            <form action="{{route('orderGroups.orderEntries.update', [$orderGroup->id, $orderEntry->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="bale_no">Loom No</label>
                    <input type="number"
                            class="form-control @error('loom_no') is-invalid @enderror"
                            name="loom_no"
                            value="{{ old('loom_no', $orderEntry->loom_no) }}"
                            placeholder="Enter Loom Number"
                            id="loom_no">
                    @error('loom_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="piece_no">Piece No</label>
                    <input type="text"
                            class="form-control @error('piece_no') is-invalid @enderror"
                            name="piece_no"
                            value="{{ old('piece_no', $orderEntry->piece_no) }}"
                            placeholder="Enter Piece Number"
                            id="piece_no">
                    @error('piece_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="meter">Meter</label>
                    <input type="number"
                            step="0.01"
                            class="form-control @error('meter') is-invalid @enderror"
                            name="meter"
                            value="{{ old('meter', $orderEntry->meter) }}"
                            placeholder="Enter Meter"
                            id="meter">
                    @error('meter')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>

@endsection