routes/web.php
<?php

use App\Http\Controllers\OrderEntriesController;
use App\Http\Controllers\OrderGroupsController;
use App\Http\Controllers\PartyInfosController;
use App\Http\Controllers\SlipsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::delete('partyInfos/trash/{partyInfo}', [PartyInfosController::class, 'trash'])->name('partyInfos.trash')->middleware(['auth']);
Route::get('partyInfos/trashed', [PartyInfosController::class, 'trashed'])->name('partyInfos.trashed')->middleware(['auth']);
Route::put('partyInfos/restore/{partyInfo}', [PartyInfosController::class, 'restore'])->name('partyInfos.restore')->middleware(['auth']);
Route::resource('partyInfos', PartyInfosController::class)->middleware(['auth']);
Route::resource('slips', SlipsController::class)->middleware(['auth']);
Route::resource('slips.orderGroups', OrderGroupsController::class)->except(['index', 'show'])->middleware(['auth']);
Route::resource('orderGroups.orderEntries', OrderEntriesController::class)->except(['index', 'show'])->middleware(['auth']);


require __DIR__ . '/auth.php';

app/Models/Slip.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slip extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    /**
     * Mutators
     */

    public function setBillDateAttribute($bill_date)
    {
        $this->attributes['bill_date'] = (new Carbon($bill_date))->format('y/m/d');
        $this->attributes['year'] = (int)explode('-', $bill_date)[0];
    }


    public function party()
    {
        return $this->belongsTo(PartyInfo::class, 'party_info_id');
    }

    public function slipGroups()
    {
        return $this->hasMany(OrderGroup::class);
    }

    public function scopeSearch($query)
    {
        $year = request('year');
        $party = request('party_id');
        $serial = request('serial_No');
        if ($year) {
            if ($party) {
                if ($serial) {
                    return $query->where('year', $year)->where('serial_no', $serial)->where('party_info_id', $party);
                }
                return $query->where('year', $year)->where('party_info_id', $party);
            }
            return $query->where('year', $year);
        }
        if ($party) {
            if ($serial) {
                return $query->where('serial_no', $serial)->where('party_info_id', $party);
            }
            return $query->where('party_info_id', $party);
        }
        if ($serial)
            return $query->where('serial_no', $serial);
    }

    public function calculateAMeter()
    {
        $this->actual_meter = ($this->total_meter - ((100 - $this->fold) * ($this->total_meter)) / 100);
        $this->save();
    }
}

app/Http/Controllers/SlipsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Slip\CreateSlipRequest;
use App\Http\Requests\Slip\UpdateSlipRequest;
use App\Models\OrderGroup;
use App\Models\Slip;
use App\Models\PartyInfo;
use Illuminate\Http\Request;

class SlipsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slips = Slip::search()->orderBy('bill_date')->paginate(4);
        $partyInfos = PartyInfo::orderBy('company_name')->get();
        return view('slip.index', compact(['slips', 'partyInfos']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $slip = Slip::orderBy('year', 'DESC')->orderBy('serial_no', 'DESC')->first();
        $partyInfos = PartyInfo::orderBy('company_name')->get();
        return view('slip.create', compact(['slip', 'partyInfos']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSlipRequest $request)
    {
        Slip::create([
            'party_info_id' => $request->party_id,
            'serial_no' => $request->serial_no,
            'bill_date' => $request->bill_date,
            'LR_NO' => $request->LR_NO,
            'delivery_at' => $request->delivery_at,
            'quality' => $request->quality,
            'user_id' => auth()->id(),
            'fold' => (int)$request->fold,
        ]);

        $slip = Slip::orderBy('id', 'DESC')->first();
        session()->flash('success', 'Slip has been created successfully!');
        return redirect(route('slips.orderGroups.create', $slip->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Slip  $slip
     * @return \Illuminate\Http\Response
     */
    public function show(Slip $slip)
    {
        return view('slip.show', compact(['slip']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Slip  $slip
     * @return \Illuminate\Http\Response
     */
    public function edit(Slip $slip)
    {
        $partyInfos = PartyInfo::orderBy('company_name')->get();
        return view('slip.edit', compact(['slip', 'partyInfos']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Slip  $slip
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSlipRequest $request, Slip $slip)
    {
        $slip->update([
            'party_info_id' => $request->party_id,
            'serial_no' => $request->serial_no,
            'bill_date' => $request->bill_date,
            'LR_NO' => $request->LR_NO,
            'delivery_at' => $request->delivery_at,
            'quality' => $request->quality,
            'user_id' => auth()->id(),
            'fold' => (int)$request->fold,
        ]);
        $ids = $slip->slipGroups->pluck('id')->toArray();
        OrderGroup::whereIn('id', $ids)->update([
            'order_group_year' => $slip->year,
        ]);
        session()->flash('success', 'Slip detail has been updated successfully!');
        return redirect(route('slips.orderGroups.create', $slip->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Slip  $slip
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slip $slip)
    {
        $slip->delete();
        session()->flash('success', 'Slip has been deleted successfully!');
        return redirect(route('slips.index'));
    }
}

resources/views/slip/create.blade.php
@extends('layouts.billGeneration.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection

@section('content')
<div class="card mx-auto mb-2 col-md-12">
    <div class="card-header"><h2>Create New Slip</h2></div>
        <div class="card-body">
            <form action="{{route('slips.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="party_id">Party Name</label>
                    <select name="party_id" id="party_id" class="form-control select2 @error('party_id') is-invalid @enderror">
                        <option></option>
                        @foreach ($partyInfos as $partyInfo)
                            @if($partyInfo->id == old('party_id'))
                                <option value="{{$partyInfo->id}}" selected>{{$partyInfo->company_name}}</option>
                            @else
                                <option value="{{$partyInfo->id}}">{{$partyInfo->company_name}}</option>
                            @endif
                        @endforeach
                        @error('party_id')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </select>
                </div>

                <div class="form-group">
                    <label for="serial_no">Serial No</label>
                    <input type="number"
                            class="form-control @error('serial_no') is-invalid @enderror"
                            name="serial_no"
                            value="{{ old('serial_no', ++$slip->serial_no) }}"
                            placeholder="Enter Serial Number"
                            id="serial_no">
                    @error('contact_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="bill_date">Slip Date</label>
                    <input type="text"
                            class="form-control"
                            name="bill_date"
                            value="{{ old('bill_date') }}"
                            id="bill_date">
                </div>

                <div class="form-group">
                    <label for="LR_NO">Tempo No/LR No.</label>
                    <input type="text"
                            class="form-control @error('LR_NO') is-invalid @enderror"
                            name="LR_NO"
                            value="{{ old('LR_NO') }}"
                            placeholder="Enter Tempo/LR Number"
                            id="LR_NO">
                    @error('LR_NO')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="delivery_at">Delivery Address</label>
                    <input type="text"
                            class="form-control @error('delivery_at') is-invalid @enderror"
                            name="delivery_at"
                            value="{{ old('delivery_at') }}"
                            placeholder="Enter Delivery Address"
                            id="delivery_at">
                    @error('delivery_at')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="quality">Quality</label>
                    <input type="text"
                            class="form-control @error('quality') is-invalid @enderror"
                            name="quality"
                            value="{{ old('quality') }}"
                            placeholder="Enter Quality"
                            id="quality">
                    @error('delivery_at')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="fold">Fold</label>
                    <input type="number"
                            class="form-control @error('fold') is-invalid @enderror"
                            name="fold"
                            value="{{ old('fold') }}"
                            placeholder="Enter Total Folds"
                            id="fold">
                    @error('fold')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        $('.select2').select2({
            placeholder: 'Select an option',
            allowClear: true
        });
        flatpickr("#bill_date", {
            enableTime: true,
            dateFormat: "Y-m-d H:i"
        });
    </script>
@endsection

resources/views/slip/edit.blade.php
@extends('layouts.billGeneration.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection

@section('content')
<div class="card mx-auto mb-2 col-md-12">
    <div class="card-header"><h2>Edit Slip</h2></div>
        <div class="card-body">
            <form action="{{route('slips.update', $slip->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="party_id">Party Name</label>
                    <select name="party_id" id="party_id" class="form-control select2  @error('party_id') is-invalid @enderror">
                        <option></option>
                        @foreach ($partyInfos as $partyInfo)
                            @if($partyInfo->id == old('party_id', $slip->party_info_id))
                                <option value="{{$partyInfo->id}}" selected>{{$partyInfo->company_name}}</option>
                            @else
                                <option value="{{$partyInfo->id}}">{{$partyInfo->company_name}}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('party_id')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="serial_no">Serial No</label>
                    <input type="number"
                            class="form-control @error('serial_no') is-invalid @enderror"
                            name="serial_no"
                            value="{{ old('serial_no', $slip->serial_no) }}"
                            placeholder="Enter Serial Number"
                            id="serial_no">
                    @error('contact_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="bill_date">Slip Date</label>
                    <input type="text"
                            class="form-control"
                            name="bill_date"
                            value="{{ old('bill_date', $slip->bill_date) }}"
                            id="bill_date">
                </div>

                <div class="form-group">
                    <label for="LR_NO">Tempo No/LR No.</label>
                    <input type="text"
                            class="form-control @error('LR_NO') is-invalid @enderror"
                            name="LR_NO"
                            value="{{ old('LR_NO', $slip->LR_NO) }}"
                            placeholder="Enter Tempo/LR Number"
                            id="LR_NO">
                    @error('LR_NO')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="delivery_at">Delivery Address</label>
                    <input type="text"
                            class="form-control @error('delivery_at') is-invalid @enderror"
                            name="delivery_at"
                            value="{{ old('delivery_at', $slip->delivery_at) }}"
                            placeholder="Enter Delivery Address"
                            id="delivery_at">
                    @error('delivery_at')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="quality">Quality</label>
                    <input type="text"
                            class="form-control @error('quality') is-invalid @enderror"
                            name="quality"
                            value="{{ old('quality', $slip->quality) }}"
                            placeholder="Enter Quality"
                            id="quality">
                    @error('delivery_at')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="fold">Fold</label>
                    <input type="number"
                            class="form-control @error('fold') is-invalid @enderror"
                            name="fold"
                            value="{{ old('fold', $slip->fold) }}"
                            placeholder="Enter Total Folds"
                            id="fold">
                    @error('fold')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        $('.select2').select2({
            placeholder: 'Select an option',
            allowClear: true
        });
        flatpickr("#bill_date", {
            enableTime: true,
            dateFormat: "Y-m-d H:i"
        });
    </script>
@endsection

resources/views/slip/index.blade.php
@extends('layouts.billGeneration.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<div class="card mx-auto col-md-10 p-2 mt-2 mb-2">
    <a href="{{route('slips.create')}}" class="btn btn-primary">Create Slip</a>
    <div class="card-header">
        <h4 class="text-center">Search</h4>
    </div>
    <div class="card-body">
        <form action="{{route('slips.index')}}" method="GET">
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label for="year">Year</label>
                    <input type="year"
                            class="form-control"
                            name="year"
                            value="{{ request('year')}}"
                            placeholder="e.g. 2019">
                </div>
                <div class="form-group col-md-6">
                    <label for="party_id">Party</label>
                    <select name="party_id" id="party_id" class="form-control select2">
                        <option></option>
                        @foreach ($partyInfos as $partyInfo)
                            @if($partyInfo->id == old('party_id'))
                                <option value="{{$partyInfo->id}}" selected>{{$partyInfo->company_name}}</option>
                            @else
                                <option value="{{$partyInfo->id}}">{{$partyInfo->company_name}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-md-3 ml-4">
                    <label for="serial_No">Serial Number</label>
                    <input type="number"
                            class="form-control d-inline"
                            name="serial_No"
                            value="{{ request('serial_no')}}"
                            placeholder="e.g. 29">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">
                Search
            </button>
        </form>
    </div>
</div>
@endsection

@section('slip-table')
<div class="card mx-auto mt-2 mb-2">
    <div class="card-body">
        @if(!$slips->count())
        No Results Found
        @endif
        @foreach ($slips as $slip)
        <a href="{{route('slips.show', $slip->id)}}" class="btn btn-warning mb-2 mr-2">
            <div class="d-inline">
                <table class="table d-inline">
                    <tr>
                        <th>Party</th>
                        <th>Serial No</th>
                        <th>Slip Date</th>
                        <th>Meter</th>
                        <th>Taga</th>
                    </tr>
                    <tr>
                        <td>{{$slip->party->company_name}}</td>
                        <td>{{$slip->serial_no}}</td>
                        <td>{{explode(" ",$slip->bill_date)[0]}}</td>
                        <td>{{$slip->total_meter}} </td>
                        <td>{{ $slip->total_piece}}</td>
                    </tr>
                </table>
            </div>
        </a>
        @endforeach
    </div>
    <div class="ml-3">
        {{ $slips->links('vendor.pagination.bootstrap-4') }}
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $('.select2').select2({
        placeholder: 'Select an option',
        allowClear: true
    });
</script>
@endsection

resources/views/slip/show.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card mx-auto col-md-12 p-2 mt-2 mb-2" id="printable">
    <a href="{{route('slips.edit', $slip->id)}}" class="btn btn-primary">Edit</a>
    <button type="submit" class="btn btn-danger" onclick="displayModal({{ $slip->id }})" data-toggle="modal" data-target="#deleteModal">Delete</button>
    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Slip</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="deleteSlipForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        Are you sure, you want to Delete this Slip?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-danger">Delete Slip</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="card-header">
            <div class="d-flex justify-content-between">
                <div></div>
                <div id="head">|| Shri Ganeshji Prasanna ||</div>
                <div class="d-flex flex-column align-items-end" id="contact">
                    <div>Off:2441177</div>
                    <div>cell:9423901111</div>
                </div>
            </div>
            <div class="d-flex justify-content-center"><strong>PACKING SLIP</strong></div>
            <div class="d-flex justify-content-center"><h4>SHRI SAI DARSHAN FABRICS</h4></div>
            <div class="d-flex justify-content-center">22/635, Ganesh Nagar, Near Sawant Process,</div>
            <div class="d-flex justify-content-center">ICHALKARANJI - 416115 Dist:-Kolhapur (Maharashtra)</div>
    </div>
    <div class="card-body">
        <div class="d-flex">
            <div class="mr-auto">No. {{$slip->serial_no}}</div>
            <div>Date :- {{explode(" ", $slip->bill_date)[0]}}</div>
        </div>
        <div>
            To - <strong>{{$slip->party->company_name}}</strong>
        </div>
        <div class="d-flex">
            <div class="mr-auto">Tempo No. / L.R. No.- <strong>{{$slip->LR_NO}}</strong></div>
            <div>Address- <strong>{{$slip->party->company_address}}</strong></div>
        </div>
        <div class="d-flex">
            <div class="mr-auto">Delivery At.- <strong>{{$slip->delivery_at}}</strong></div>
            <div>Quality- <strong>{{$slip->quality}}</strong></div>
        </div>
        <div class="d-flex">
            <div class="mr-auto">GST- {{$slip->party->GST_no}}</div>
            <div>State- <strong>{{$slip->party->state}}</strong></div>
        </div>
        <div class="d-flex justify-content-center border border-dark flex-row mt-2">
            <div class="d-none">{{$i=0}}{{$row=0}}</div>
            <div class="">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Sr.No</th>
                            <th>Loom No</th>
                            <th>Piece No.</th>
                            <th>Meter</th>
                            <th>Bale No.</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($slip->slipGroups as $index=>$slipGroup)
                        @foreach ($slipGroup->baleEntries as $key=>$baleEntry)
                        @if ($row >= 30)
                            @break;
                        @endif
                        <tr>
                            <td>{{++$i}}</td>
                            <td>{{ $baleEntry->loom_no }}</td>
                            <td>{{$baleEntry->piece_no}}</td>
                            <td>{{$baleEntry->meter}}</td>
                            <div class="d-none">{{++$row}}</div>
                            @if (++$key == round($slipGroup->baleEntries->count()/2))
                            <td><strong>{{$slipGroup->bale_no}}</strong></td>
                            @else
                            <td></td>
                            @endif
                        </tr>
                        @endforeach
                        @if($row >= 30)
                        @break
                        @else
                        <tr>
                            <td colspan="3"></td>
                            <div class="d-none">{{++$row}}</div>
                            <td><strong>{{$slipGroup->group_total_meter}}</strong></td>
                        </tr>
                        @endif
                        @endforeach
                    </tbody>

                </table>
            </div>
            <div class="d-none">{{$rows=0}}</div>
            <div class="">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Sr.No</th>
                            <th>Loom No</th>
                            <th>Piece No.</th>
                            <th>Meter</th>
                            <th>Bale No.</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($slip->slipGroups as $index=>$slipGroup)
                        @foreach ($slipGroup->baleEntries as $key=>$baleEntry)
                        @if ($rows <= 29)
                            <div class="d-none">{{++$rows}}</div>
                        @else
                        <tr>
                            <td>{{++$i}}</td>
                            <td>{{ $baleEntry->loom_no }}</td>
                            <td>{{$baleEntry->piece_no}}</td>
                            <td>{{$baleEntry->meter}}</td>
                            <div class="d-none">{{++$rows}}</div>
                            @if (++$key == round($slipGroup->baleEntries->count()/2))
                            <td><strong>{{$slipGroup->bale_no}}</strong></td>
                            @else
                            <td></td>
                            @endif
                        </tr>
                        @endif
                        @endforeach
                        @if($rows <= 29)
                        <div class="d-none">{{++$rows}}</div>
                        @else
                        <tr>
                            <td colspan="3"></td>
                            <div class="d-none">{{++$rows}}</div>
                            <td><strong>{{$slipGroup->group_total_meter}}</strong></td>
                        </tr>
                        @endif
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex flex-row">
            <div class="d-flex flex-column">
                <div class="">Total Taga: {{$slip->total_piece}} Taga</div>
                <div class="">Fold: {{$slip->fold}}</div>
            </div>
            <div class="d-flex flex-column ml-5">
                <div>Total Meter: {{$slip->total_meter}}</div>
                <div class="">Actual Meter: {{$slip->actual_meter}}</div>
            </div>
            <div class="d-flex flex-column ml-auto">
                <div></div>
                <div class="mt-auto"><strong>For - Shri Sai Darshan Fabrics</strong></div>
            </div>
        </div>
        </div>
    </div>
</div>
<div class="mb-2">
    <button class="btn btn-warning" onclick="{{$slip->calculateAMeter()}}">Calculate</button>
    <button class="btn btn-success" onclick="generatePDF()">Print</button>
</div>
@endsection

@section('page-level-styles')
    <style>
        #head{
            position: relative;
            left: 3.5em;
        }
    </style>
@endsection

@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.8.0/html2pdf.bundle.js" integrity="sha512-VqCeCECsaE2fYTxvPQk+OJ7+SQxzI1xZ6IqxuWd0GPKaJoeSFqeakVqNpMbx1AArieciBF71poL0dYTMiNgVxA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    function generatePDF() {
      // Choose the element that our invoice is rendered in.
      const element = document.getElementById("printable");
      console.log(element);
      // Choose the element and save the PDF for our user.
      html2pdf().from(element).save();
    }
    function displayModal(slipId) {
        var url = "/slips/" + slipId;
        $("#deleteSlipForm").attr('action', url);
    }
  </script>
@endsection