routes/web.php
<?php

use App\Http\Controllers\OrderEntriesController;
use App\Http\Controllers\OrderGroupsController;
use App\Http\Controllers\PartyInfosController;
use App\Http\Controllers\SlipsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::delete('partyInfos/trash/{partyInfo}', [PartyInfosController::class, 'trash'])->name('partyInfos.trash')->middleware(['auth']);
Route::get('partyInfos/trashed', [PartyInfosController::class, 'trashed'])->name('partyInfos.trashed')->middleware(['auth']);
Route::put('partyInfos/restore/{partyInfo}', [PartyInfosController::class, 'restore'])->name('partyInfos.restore')->middleware(['auth']);
Route::resource('partyInfos', PartyInfosController::class)->middleware(['auth']);
Route::resource('slips', SlipsController::class)->middleware(['auth']);
Route::resource('slips.orderGroups', OrderGroupsController::class)->except(['index', 'show'])->middleware(['auth']);
Route::resource('orderGroups.orderEntries', OrderEntriesController::class)->except(['index', 'show'])->middleware(['auth']);


require __DIR__ . '/auth.php';

app/Models/OrderGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderGroup extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public static function boot()
    {
        parent::boot();
        static::created(function (OrderGroup $orderGroup) {
            $orderGroup->order_group_year = $orderGroup->slip->year;
            $orderGroup->save();
        });
        static::deleted(function (OrderGroup $orderGroup) {
            $meter = $orderGroup->group_total_meter;
            $orderGroup->slip->update([
                'total_meter' => $orderGroup->slip->total_meter - $meter,
            ]);
        });
    }

    public function setBaleNoAttribute($value)
    {
        $this->attributes['bale_no'] = (int)$value;
        //$this->attributes['order_group_year'] = $this->slip->year;
    }

    public function slip()
    {
        return $this->belongsTo(Slip::class, 'slip_id');
    }

    public function baleEntries()
    {
        return $this->hasMany(OrderEntry::class);
    }
}

app/Http/Controllers/OrderGroupsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderGroup\CreateOrderGroupRequest;
use App\Models\OrderGroup;
use App\Models\Slip;
use Illuminate\Http\Request;

class OrderGroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Slip $slip)
    {
        $orderGroup = OrderGroup::orderBy('order_group_year', 'DESC')->orderBy('bale_no', 'DESC')->first();
        return view('orderGroup.create', compact(['slip', 'orderGroup']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateOrderGroupRequest $request, Slip $slip)
    {
        $slip->slipGroups()->create([
            'bale_no' => $request->bale_no
        ]);

        $orderGroup = OrderGroup::orderBy('id', 'DESC')->first();
        session()->flash('success', 'Bale has been created successfully!');
        return redirect(route('orderGroups.orderEntries.create', $orderGroup->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\OrderGroup  $orderGroup
     * @return \Illuminate\Http\Response
     */
    public function show(OrderGroup $orderGroup)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\OrderGroup  $orderGroup
     * @return \Illuminate\Http\Response
     */
    public function edit(Slip $slip, OrderGroup $orderGroup)
    {
        return view('orderGroup.edit', compact(['orderGroup', 'slip']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\OrderGroup  $orderGroup
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slip $slip, OrderGroup $orderGroup)
    {
        $orderGroup->update([
            'bale_no' => $request->bale_no,
        ]);
        session()->flash('success', 'Bale has Updated created successfully!');
        return redirect(route('orderGroups.orderEntries.create', compact(['orderGroup'])));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\OrderGroup  $orderGroup
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slip $slip, OrderGroup $orderGroup)
    {
        $piece = sizeOf($orderGroup->baleEntries->pluck('id')->toArray());
        $orderGroup->slip->update([
            'total_piece' => $orderGroup->slip->total_piece - $piece,
        ]);
        $orderGroup->delete();
        session()->flash('success', 'Bale has Deleted successfully!');
        return redirect(route('slips.orderGroups.create', compact(['slip'])));
    }
}

resources/views/orderGroup/create.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card mb-2 col-md-5">
    <div class="card-header"><h2>Create New Bale</h2></div>
        <div class="card-body">
            <form action="{{route('slips.orderGroups.store', $slip->id)}}" method="POST">
                @csrf

                <div class="form-group">
                    <label for="bale_no">Bale No</label>
                    <input type="number"
                            class="form-control @error('bale_no') is-invalid @enderror"
                            name="bale_no"
                            value="{{ old('bale_no', ++$orderGroup->bale_no) }}"
                            placeholder="Enter Bale Number"
                            id="bale_no">
                    @error('bale_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
@if($slip->slipGroups->count())
<div class="card mx-auto mb-2 col-md-12">
    <a href="{{route('slips.show', $slip->id)}}" class="mt-2 btn btn-success">Complete Preview Slip</a>
    <div class="card-header"><h2>Existing Bales</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Bale No</th>
                        <th>Total Meter</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($slip->slipGroups as $slipGroup)
                        <tr>
                            <td>{{$slipGroup->bale_no}}</td>
                            <td>{{$slipGroup->group_total_meter}}</td>
                            <td>
                                <a href="{{route('slips.orderGroups.edit',[$slip->id, $slipGroup->id])}}" class="btn btn-sm btn-primary mb-1">
                                    Edit
                                </a>
                                <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{$slip->id}}, {{$slipGroup->id}})" data-toggle="modal" data-target="#deleteModal">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- Delete Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Trash Party</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="" method="POST" id="deleteBaleForm">
                        @csrf
                        @method('DELETE')
                        <div class="modal-body">
                            Are you sure, you want to Delete this Bale?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-outline-danger">Delete Bale</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endif
@endsection

@section('page-level-scripts')
<script>
    function displayModal(slipId, baleId) {
        var url = "/slips/" + slipId + "/orderGroups/" + baleId;
        $("#deleteBaleForm").attr('action', url);
    }
</script>
@endsection

resources/views/orderGroup/edit.blade.php
@extends('layouts.billGeneration.app')

@section('content')
<div class="card mb-2 col-md-5">
    <div class="card-header"><h2>Edit Bale</h2></div>
        <div class="card-body">
            <form action="{{route('slips.orderGroups.update', [$slip->id, $orderGroup->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="bale_no">Bale No</label>
                    <input type="number"
                            class="form-control @error('bale_no') is-invalid @enderror"
                            name="bale_no"
                            value="{{ old('bale_no', $orderGroup->bale_no) }}"
                            placeholder="Enter Bale Number"
                            id="bale_no">
                    @error('bale_no')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection